#!/usr/bin/env node
/**
 * 生成探针页面（native-android-companion 的 tasks 2.6 / 2.7 / 2.8）。
 *
 * ## 这页要回答三个只有真机能答的问题
 *
 *   2.6 `UsageStatsManager` 能否稳定拿到 7 天数据？`queryUsageStats` 还是 `queryEvents`？
 *   2.7 通知监听能否拿到微信/支付宝支付通知？原文长什么样？
 *   2.8 精确闹钟在息屏/省电下能否到点弹出？`setExactAndAllowWhileIdle` vs `setAlarmClock`？
 *
 * ## 设计纪律（沿用 v2 的教训）
 *
 * v1 的探针第一行就解构 `window.Capacitor`，无 try/catch，桥缺失时整页脚本不执行，
 * 连"我挂了"都显示不出来。因此本版保持：
 *   1. 第一个内联经典脚本同步写下「探针已启动」，证明脚本确实在执行
 *   2. 全程 try/catch，异常写进 DOM
 *   3. 不预设任何全局或插件存在；缺失本身就是结论
 *   4. 每次原生调用都带超时——原生不回时不能让界面无声挂起
 *   5. **如实报告失败原因**，不做补偿或猜测：探针的价值在于暴露真相
 *
 * 生成目标：apps/android-cap/www/index.html
 *
 * 探针页顶部的「脚注」约定：本页每个测试小节都自己回查并给出通过/失败判定，
 * 不依赖人去记得点刷新。**需要人记住步骤的探针，验证结果就不可靠**——
 * 这是把闹钟测试改成"排完自己等 16 秒再回查"的原因。
 *
 * 可选参数：
 *   --out <path>   额外写到指定路径（相对 android-cap 根）
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const capRoot = resolve(here, '..');
const outDir = resolve(capRoot, 'www');
const outFile = resolve(outDir, 'index.html');

mkdirSync(outDir, { recursive: true });

// 刻意用普通字符串拼接而非模板字符串：避免被注入内容里的 ${...} 被求值。
const html = [
  '<!doctype html>',
  '<html lang="zh-CN">',
  '<head>',
  '<meta charset="utf-8" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1" />',
  '<title>WebBook 宿主 · 原生能力探针</title>',
  '<style>',
  '  :root { color-scheme: dark; }',
  '  body { margin:0; padding:14px 14px 80px; background:#0f172a; color:#e2e8f0;',
  '         font:13px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; }',
  '  h1 { font-size:16px; margin:0 0 12px; }',
  '  h2 { font-size:13px; margin:20px 0 8px; color:#94a3b8;',
  '       border-top:1px solid #1e293b; padding-top:12px; }',
  '  .box { padding:11px; border-radius:8px; margin:10px 0; font-weight:700; }',
  '  .pass { background:#064e3b; border:1px solid #10b981; }',
  '  .fail { background:#7f1d1d; border:1px solid #ef4444; }',
  '  .warn { background:#78350f; border:1px solid #f59e0b; }',
  '  .info { background:#1e293b; border:1px solid #475569; font-weight:400; }',
  '  table { border-collapse:collapse; width:100%; }',
  '  th,td { text-align:left; padding:5px 7px; border-bottom:1px solid #1e293b;',
  '          vertical-align:top; word-break:break-all; }',
  '  th { color:#94a3b8; font-weight:600; width:42%; }',
  '  pre { background:#020617; padding:9px; border-radius:6px; overflow-x:auto;',
  '        font-size:11px; white-space:pre-wrap; }',
  '  button { margin:4px 6px 4px 0; padding:8px 13px; border-radius:6px; border:0;',
  '           background:#2563eb; color:#fff; font:inherit; font-size:12px; }',
  '  button.alt { background:#334155; }',
  '  button:disabled { opacity:.45; }',
  '  .row { display:flex; flex-wrap:wrap; align-items:center; gap:6px; }',
  '  .hint { color:#94a3b8; font-weight:400; font-size:12px; }',
  '  .ok { color:#6ee7b7; } .bad { color:#fca5a5; } .wa { color:#fcd34d; }',
  '</style>',
  '</head>',
  '<body>',
  '<h1>WebBook 宿主 · 原生能力探针</h1>',
  // 脚本执行的最开始就被改写。若一直停在「脚本未启动」，说明 <script> 根本没跑。
  '<div id="boot" class="box info">脚本未启动…</div>',
  '<div id="verdict" class="box info">等待初始化…</div>',
  '<button id="refreshAll">刷新全部状态</button>',
  '',
  '<h2>① 环境与权限</h2>',
  '<table id="facts"><tr><th>（待采集）</th><td></td></tr></table>',
  '<div class="row">',
  '  <button id="openUsage" class="alt">打开「使用情况访问」设置</button>',
  '  <button id="openListener" class="alt">打开「通知使用权」设置</button>',
  '  <button id="openAlarm" class="alt">打开「闹钟和提醒」设置</button>',
  '</div>',
  '<p class="hint">授权后回到本页点「刷新全部状态」。三项互相独立，缺一项不影响其余。</p>',
  '',
  '<h2>② 使用统计（2.6）</h2>',
  '<div class="row">',
  '  <input id="usageDate" type="date" style="padding:7px;border-radius:6px;border:1px solid #334155;background:#020617;color:#e2e8f0;font:inherit" />',
  '  <button id="runUsage">queryUsageStats</button>',
  '  <button id="runEvents" class="alt">queryEvents</button>',
  '</div>',
  '<div id="usageVerdict" class="box info">未运行</div>',
  '<table id="usageTable"><tr><th>（待采集）</th><td></td></tr></table>',
  '<pre id="usageRaw" style="display:none"></pre>',
  '',
  '<h2>③ 支付通知监听（2.7）</h2>',
  '<div class="row">',
  '  <button id="drainNotify">取走通知</button>',
  '  <button id="autoDrain" class="alt">开始每 3 秒自动取</button>',
  '</div>',
  '<div id="notifyVerdict" class="box info">未运行</div>',
  '<table id="notifyTable"><tr><th>（待采集）</th><td></td></tr></table>',
  '<p class="hint">请先用微信/支付宝完成一笔真实支付（或让朋友转你 0.01 元），再点「取走通知」。</p>',
  '<pre id="notifyList">（空）</pre>',
  '',
  '<h2>④ 精确闹钟（2.8）</h2>',
  '<div class="row">',
  '  <button id="alarmExact">exact · 10 秒</button>',
  '  <button id="alarmClock">alarmClock · 10 秒</button>',
  '  <button id="alarmInexact" class="alt">inexact · 10 秒（对照）</button>',
  '</div>',
  '<p class="hint">排好后<strong>息屏</strong>等待。到点应弹出系统通知；回到本页点「刷新全部状态」看「最近触发」。</p>',
  '<div id="alarmVerdict" class="box info">未排程</div>',
  '',
  '<h2>⑤ 执行轨迹</h2>',
  '<pre id="trace">（空）</pre>',
  '',
  '<script>',
  '/* 经典脚本、非 module、内联在 body —— 保证先于下面的 module 执行。',
  '   目的只有一个：把「脚本确实启动了」这条最基础的事实立刻写进 DOM。 */',
  '(function () {',
  '  var el = document.getElementById("boot");',
  '  if (el) { el.className = "box pass"; el.textContent = "① 脚本已启动（经典内联脚本执行成功）"; }',
  '})();',
  '</script>',
  '',
  '<script type="module">',
  'const T = { log: [] };',
  'function trace(msg) {',
  '  T.log.push(new Date().toISOString().slice(11, 23) + "  " + msg);',
  '  const el = document.getElementById("trace");',
  '  if (el) el.textContent = T.log.slice(-40).join("\\n");',
  '}',
  'function setBox(id, cls, text) {',
  '  const el = document.getElementById(id);',
  '  if (el) { el.className = "box " + cls; el.textContent = text; }',
  '}',
  'function renderTable(id, rows) {',
  '  const t = document.getElementById(id);',
  '  if (!t) return;',
  '  t.innerHTML = rows.map(function (r) {',
  '    return "<tr><th>" + String(r[0]).replace(/</g, "&lt;") + "</th><td>" +',
  '           String(r[1]).replace(/</g, "&lt;") + "</td></tr>";',
  '  }).join("");',
  '}',
  'function safe(fn, fallback) {',
  '  try { return fn(); } catch (e) { return "‹异常: " + (e && e.message ? e.message : e) + "›"; }',
  '}',
  '',
  '/* 原生调用一律带超时：原生不回时不能让界面无声挂起 */',
  'function withTimeout(promise, ms, label) {',
  '  return Promise.race([',
  '    promise,',
  '    new Promise(function (_, rej) {',
  '      setTimeout(function () { rej(new Error(label + " 超时（" + ms + "ms）")); }, ms);',
  '    }),',
  '  ]);',
  '}',
  '',
  'let Probe = null;',
  'let bridgeError = null;',
  '',
  'function initBridge() {',
  '  const rows = [];',
  '  rows.push(["typeof window.Capacitor", safe(function () { return typeof window.Capacitor; })]);',
  '  if (!window.Capacitor) {',
  '    bridgeError = "window.Capacitor 不存在——native 未注入运行时";',
  '    return { rows: rows, cap: null };',
  '  }',
  '  const cap = window.Capacitor;',
  '  rows.push(["Capacitor.getPlatform()", safe(function () { return cap.getPlatform(); })]);',
  '  rows.push(["isNativePlatform()", safe(function () { return String(cap.isNativePlatform()); })]);',
  '  rows.push(["isPluginAvailable(Probe)", safe(function () { return String(cap.isPluginAvailable("Probe")); })]);',
  '  try {',
  '    Probe = cap.Plugins && cap.Plugins.Probe ? cap.Plugins.Probe : cap.registerPlugin("Probe");',
  '  } catch (e) {',
  '    bridgeError = "注册 Probe 插件失败：" + e.message;',
  '  }',
  '  return { rows: rows, cap: cap };',
  '}',
  '',
  'async function callProbe(method, args, timeoutMs) {',
  '  if (!Probe) throw new Error(bridgeError || "Probe 插件不可用");',
  '  return await withTimeout(Probe[method](args || {}), timeoutMs || 15000, method);',
  '}',
  '',
  '/* ══════════════ ① 环境与权限 ══════════════ */',
  'async function refreshSnapshot() {',
  '  const init = initBridge();',
  '  const rows = init.rows.slice();',
  '  if (!Probe) {',
  '    renderTable("facts", rows);',
  '    setBox("verdict", "fail", "失败：" + (bridgeError || "插件不可用"));',
  '    return;',
  '  }',
  '  let snap = null;',
  '  try {',
  '    snap = await callProbe("snapshot", {}, 8000);',
  '  } catch (e) {',
  '    rows.push(["Probe.snapshot()", "‹失败: " + e.message + "›"]);',
  '    renderTable("facts", rows);',
  '    setBox("verdict", "fail", "插件可达但 snapshot 调用失败：" + e.message);',
  '    return;',
  '  }',
  '  rows.push(["nativeSdkInt", snap.nativeSdkInt]);',
  '  rows.push(["机型", snap.nativeDevice]);',
  '  rows.push(["Android 版本", snap.nativeRelease]);',
  '  rows.push(["时区", snap.timezone]);',
  '  rows.push(["设备当前时间", snap.nowLocal]);',
  '  rows.push(["—— 权限 ——", ""]);',
  '  rows.push(["使用情况访问", snap.usageGranted ? "已授予 ✓" : "未授予 ✗"]);',
  '  rows.push(["通知使用权（已授权）", snap.notifyListenerGranted ? "已授予 ✓" : "未授予 ✗"]);',
  '  rows.push(["通知监听（已连接）", snap.notifyListenerConnected ? "已连接 ✓" : "未连接 ✗"]);',
  '  rows.push(["监听断开次数", snap.notifyListenerDisconnects]);',
  '  rows.push(["通知展示权限", snap.canPostNotifications ? "允许 ✓" : "被拒 ✗"]);',
  '  rows.push(["精确闹钟（canScheduleExactAlarms）", snap.canScheduleExactAlarms ? "允许 ✓" : "被拒 ✗"]);',
  '  rows.push(["—— 监听计数 ——", ""]);',
  '  rows.push(["收到的通知总数", snap.notificationsSeen]);',
  '  rows.push(["其中微信/支付宝", snap.notificationsKept]);',
  '  rows.push(["缓冲中待取", snap.notificationsBuffered]);',
  '  rows.push(["最近一次闹钟触发", snap.lastAlarmFired]);',
  '  if (snap.grantedListeners && snap.grantedListeners.length) {',
  '    rows.push(["已授权的监听器", snap.grantedListeners.join("\\n")]);',
  '  }',
  '  renderTable("facts", rows);',
  '',
  '  const usageOk = !!snap.usageGranted;',
  '  const notifyOk = !!snap.notifyListenerConnected;',
  '  const alarmOk = !!snap.canScheduleExactAlarms && !!snap.canPostNotifications;',
  '  const cls = (usageOk && notifyOk && alarmOk) ? "pass" : (usageOk || notifyOk || alarmOk ? "warn" : "fail");',
  '  setBox("verdict", cls,',
  '    "使用统计 " + (usageOk ? "✓" : "✗") +',
  '    " · 通知监听 " + (notifyOk ? "✓" : "✗") +',
  '    " · 精确闹钟 " + (alarmOk ? "✓" : "✗") +',
  '    "  —— 三项独立，缺哪项就看对应小节的说明");',
  '  trace("snapshot 完成");',
  '}',
  '',
  '/* ══════════════ ② 使用统计 ══════════════ */',
  'async function runUsage(kind) {',
  '  const dateEl = document.getElementById("usageDate");',
  '  const date = (dateEl && dateEl.value) || new Date(Date.now() - 86400000).toISOString().slice(0, 10);',
  '  const method = kind === "events" ? "usageEvents" : "usageDaily";',
  '  setBox("usageVerdict", "info", "正在调用 " + method + " …");',
  '  trace(method + " " + date);',
  '  let r = null;',
  '  try {',
  '    r = await callProbe(method, { date: date }, 20000);',
  '  } catch (e) {',
  '    setBox("usageVerdict", "fail", method + " 调用失败：" + e.message);',
  '    return;',
  '  }',
  '  const rows = [];',
  '  rows.push(["date", r.date]);',
  '  rows.push(["granted", String(r.granted)]);',
  '  if (r.error) rows.push(["error", r.error]);',
  '  rows.push(["统计到的应用数（有时长）", r.appCount]);',
  '  rows.push(["前台总时长", fmtMs(r.totalMs)]);',
  '  if (kind === "events") {',
  '    rows.push(["扫描事件数", r.scannedEvents]);',
  '  } else {',
  '    rows.push(["原始桶数", r.rawBucketCount]);',
  '    rows.push(["查询区间", r.queryStart + " → " + r.queryEnd]);',
  '    rows.push(["桶实际跨度", (r.bucketFirst || "?") + " → " + (r.bucketLast || "?")]);',
  '  }',
  '  if (Array.isArray(r.apps)) {',
  '    r.apps.slice(0, 15).forEach(function (a, i) {',
  '      rows.push(["#" + (i + 1) + " " + a.label, fmtMs(a.ms) + (a.launches ? " · " + a.launches + " 次" : "")]);',
  '    });',
  '  }',
  '  renderTable("usageTable", rows);',
  '  const raw = document.getElementById("usageRaw");',
  '  if (raw) { raw.style.display = "block"; raw.textContent = JSON.stringify(r, null, 2); }',
  '',
  '  const ok = Array.isArray(r.apps) && r.apps.length > 0 && r.totalMs > 0;',
  '  setBox("usageVerdict", ok ? "pass" : "fail",',
  '    ok ? (method + " 可用：拿到 " + r.apps.length + " 个应用、" + fmtMs(r.totalMs))',
  '       : (method + " 没拿到有效数据" + (r.error ? "：" + r.error : "（应用数为 0 或总时长为 0）")));',
  '}',
  '',
  'function fmtMs(ms) {',
  '  if (typeof ms !== "number" || !isFinite(ms) || ms <= 0) return "0";',
  '  const m = Math.round(ms / 60000);',
  '  const h = Math.floor(m / 60);',
  '  return h > 0 ? (h + " 小时 " + (m % 60) + " 分") : (m + " 分钟");',
  '}',
  '',
  '/* ══════════════ ③ 支付通知 ══════════════ */',
  'let autoTimer = null;',
  'async function drainNotify() {',
  '  let r = null;',
  '  try {',
  '    r = await callProbe("drainNotifications", {}, 10000);',
  '  } catch (e) {',
  '    setBox("notifyVerdict", "fail", "drainNotifications 失败：" + e.message);',
  '    return;',
  '  }',
  '  const list = Array.isArray(r.notifications) ? r.notifications : [];',
  '  const pre = document.getElementById("notifyList");',
  '  if (pre) {',
  '    pre.textContent = list.length ? list.map(function (n, i) {',
  '      return "[" + (i + 1) + "] source=" + n.source + "  pkg=" + n.pkg +',
  '             "\\n    title: " + JSON.stringify(n.title) +',
  '             "\\n    text : " + JSON.stringify(n.text) +',
  '             "\\n    postedAt: " + n.postedAt;',
  '    }).join("\\n\\n") : "（本轮没有新通知；总数 " + r.totalKept + " 条微信/支付宝）";',
  '  }',
  '  const rows = [];',
  '  rows.push(["通知使用权已授权", String(r.granted)]);',
  '  rows.push(["监听已连接", String(r.connected)]);',
  '  rows.push(["断开次数", r.disconnects]);',
  '  rows.push(["累计收到通知", r.totalSeen]);',
  '  rows.push(["其中微信/支付宝", r.totalKept]);',
  '  rows.push(["本次取走", list.length]);',
  '  renderTable("notifyTable", rows);',
  '',
  '  if (!r.granted) {',
  '    setBox("notifyVerdict", "fail", "未授予「通知使用权」——系统不会绑定监听服务，且不会报错。请点上面按钮去设置里开启。");',
  '  } else if (!r.connected) {',
  '    setBox("notifyVerdict", "warn", "已授权但监听未连接——可能刚授权完还没重绑，杀掉应用重开一次。");',
  '  } else if (list.length > 0) {',
  '    setBox("notifyVerdict", "pass", "拿到 " + list.length + " 条微信/支付宝通知，原文见下方。");',
  '  } else {',
  '    setBox("notifyVerdict", "info", "已连接，但没有待取通知。请先完成一笔真实支付再取。");',
  '  }',
  '}',
  '',
  '/* ══════════════ ④ 精确闹钟 ══════════════ */',
  '',
  '/* 排程后自己等到触发时刻再回查，不依赖人去记得点刷新。',
  '   这是"能不能当测试用"的关键：需要人记住步骤的探针，验证结果就不可靠。 */',
  'function delay(ms) { return new Promise(function (r) { setTimeout(r, ms); }); }',
  '',
  'async function scheduleAlarm(mode) {',
  '  const seconds = 10;',
  '  const id = "probe-" + mode + "-" + Date.now();',
  '  setBox("alarmVerdict", "info", "正在排 " + mode + " …");',
  '  let r = null;',
  '  try {',
  '    r = await callProbe("scheduleAlarm", { seconds: seconds, mode: mode, id: id }, 8000);',
  '  } catch (e) {',
  '    setBox("alarmVerdict", "fail", "scheduleAlarm 失败：" + e.message);',
  '    return;',
  '  }',
  '  if (r.error) {',
  '    setBox("alarmVerdict", "fail", "排程失败：" + r.error + (r.exactAllowed === false ? "（精确闹钟权限未授予）" : ""));',
  '    return;',
  '  }',
  '  setBox("alarmVerdict", "info",',
  '    "已排 " + r.mode + "，将于 " + r.triggerAtLocal + " 触发。请现在息屏，界面会自动等待并回报结果…");',
  '  if (r.canPostNotifications === false) {',
  '    trace("警告：通知展示权限被拒——闹钟会触发但看不到通知");',
  '  }',
  '  await delay((seconds + 6) * 1000);',
  '  let snap = null;',
  '  try {',
  '    snap = await callProbe("snapshot", {}, 8000);',
  '  } catch (e) {',
  '    setBox("alarmVerdict", "warn", "排程成功，但回查失败：" + e.message + "（请手动点「刷新全部状态」）");',
  '    return;',
  '  }',
  '  const fired = String(snap.lastAlarmFired || "");',
  '  const hit = fired.indexOf(id) === 0;',
  '  if (hit) {',
  '    setBox("alarmVerdict", "pass",',
  '      mode + " 按时触发 ✓（" + fired + "）。若刚才屏幕是黑的且现在看到了通知，说明息屏下也能到点。");',
  '  } else {',
  '    setBox("alarmVerdict", "fail",',
  '      mode + " 未触发或未记录 ✗（最近一次触发：" + fired + "）。可能被系统省电策略延迟/拦截，或未授予精确闹钟权限。");',
  '  }',
  '  trace("闹钟回查：" + mode + " hit=" + hit);',
  '}',
  '',
  '/* ══════════════ 绑定 ══════════════ */',
  'async function main() {',
  '  try {',
  '    await refreshSnapshot();',
  '  } catch (e) {',
  '    setBox("verdict", "fail", "探针自身异常（非桥的问题）：" + (e && e.message ? e.message : e));',
  '    trace("未捕获异常：" + (e && e.stack ? e.stack : e));',
  '  }',
  '}',
  '',
  'function bind(id, fn) {',
  '  try {',
  '    const el = document.getElementById(id);',
  '    if (el) el.addEventListener("click", fn);',
  '  } catch (e) { trace("绑定 " + id + " 失败：" + e.message); }',
  '}',
  '',
  'try {',
  '  const d = document.getElementById("usageDate");',
  '  if (d) d.value = new Date(Date.now() - 86400000).toISOString().slice(0, 10);',
  '  bind("refreshAll", function () { main(); });',
  '  bind("openUsage", function () { callProbe("openSettings", { which: "usage" }, 6000).catch(function (e) { trace("打开设置失败：" + e.message); }); });',
  '  bind("openListener", function () { callProbe("openSettings", { which: "notifyListener" }, 6000).catch(function (e) { trace("打开设置失败：" + e.message); }); });',
  '  bind("openAlarm", function () { callProbe("openSettings", { which: "exactAlarm" }, 6000).catch(function (e) { trace("打开设置失败：" + e.message); }); });',
  '  bind("runUsage", function () { runUsage("stats"); });',
  '  bind("runEvents", function () { runUsage("events"); });',
  '  bind("drainNotify", function () { drainNotify(); });',
  '  bind("autoDrain", function () {',
  '    const btn = document.getElementById("autoDrain");',
  '    if (autoTimer) {',
  '      clearInterval(autoTimer); autoTimer = null;',
  '      if (btn) btn.textContent = "开始每 3 秒自动取";',
  '      trace("已停止自动取");',
  '    } else {',
  '      autoTimer = setInterval(function () { drainNotify(); }, 3000);',
  '      if (btn) btn.textContent = "停止自动取";',
  '      trace("已开始每 3 秒自动取");',
  '    }',
  '  });',
  '  bind("alarmExact", function () { scheduleAlarm("exact"); });',
  '  bind("alarmClock", function () { scheduleAlarm("clock"); });',
  '  bind("alarmInexact", function () { scheduleAlarm("inexact"); });',
  '  trace("按钮监听已绑定");',
  '} catch (e) {',
  '  trace("绑定阶段异常：" + e.message);',
  '}',
  '',
  'main();',
  '</script>',
  '</body>',
  '</html>',
  '',
].join('\n');

writeFileSync(outFile, html, 'utf8');
console.log('✓ 探针页面已生成: ' + outFile);
console.log('  ' + html.length + ' 字节（原生能力探针：使用统计 / 通知监听 / 精确闹钟）');

const outFlag = process.argv.indexOf('--out');
if (outFlag !== -1 && process.argv[outFlag + 1]) {
  const extra = resolve(capRoot, process.argv[outFlag + 1]);
  mkdirSync(dirname(extra), { recursive: true });
  writeFileSync(extra, html, 'utf8');
  console.log('✓ 额外输出: ' + extra);
}

console.log('  下一步: node scripts/android-cap-apk.mjs --probe');
